name: cyphal_init.sh

on: [push]
jobs:
  cyphal_init:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Install
        run: |
          sudo apt-get update
          sudo apt-get install -y linux-modules-extra-$(uname -r)
          python3 -m pip install yakut

      - uses: actions/checkout@v3
        with:
          path: 'repository'

      - uses: actions/checkout@v3
        with:
          repository: OpenCyphal/public_regulated_data_types
          path: 'repository/public_regulated_data_types'

      - name: Create VCAN and compile DSDL 
        run: |
          source repository/cyphal/init.sh --interface slcan0 --node-id 127 -v

      - name: Check Yakut result 
        run: |
          source repository/cyphal/init.sh -i slcan0 -n 127 -v
          timeout --verbose --preserve-status 3 y mon > yakut_output.txt || true
          cat yakut_output.txt
